### PR TITLE
Add request DELETE

### PR DESCRIPTION
**Pull request by kikemarto**
Request type DELETE added

### CODE REVIEW

**Comment by kikemarto** [comment]
The DELETE method to validate the authentication needs to know who deleted. the token is needed.

The GET method does not require the token.

**Comment by mbarwick83** [comment]
No, authentication option in POST is specifically for oAuth purposes. For GET (and now DELETE), tokens are automatically included with each call automatically. :)

**Comment by kikemarto** [comment]
Ready. :) Review.

**Comment by mbarwick83** [comment]
Cheers, thanks!

**Pull request merged**
